#!/bin/sh

port="sudo port -f"

${port} selfupdate
${port} install \
    cairo +quartz-x11 \
    pango +quartz-x11 \
    gdk-pixbuf2 -x11 \
    gtk2 +quartz-x11 \
    gtkmm \
    gtk-engines2 \
    lcms2 \
    libiptcdata \
    fftw-3-single \
    gcc47 \
    cmake \
    mercurial
