#!/bin/sh

port="sudo port"

# UPDATE MACPORTS
# sudo port selfupdate

${port} install \
    cairo +quartz \
    pango +quartz \
    gtk2 +quartz \
	libsigcxx2

# gtkmm binary build failed. add source build option.
${port} -s install gtkmm

${port} install \
    gtk-engines2 \
    lcms2 \
    libiptcdata \
    fftw-3-single \
    gcc47 \
    cmake \
    mercurial
