#!/bin/bash

bundle_dir=$(dirname "$0")
echo "${bundle_dir}"

bundle=$(cd "${bundle_dir}/../../" && pwd)
echo "${bundle}"

export DYLD_LIBRARY_PATH="${bundle_dir}/lib:$DYLD_LIBRARY_PATH"
export FONTCONFIG_PATH="${bundle_dir}/etc/fonts"
export GDK_PIXBUF_MODULE_FILE="${bundle_dir}/etc/gtk-2.0/gdk-pixbuf.loaders"
export GTK2_RC_FILES="${bundle_dir}/etc/gtk-2.0/gtkrc"
export GTK_DATA_DIRS="${bundle_dir}"
export GTK_DATA_PREFIX="${bundle_dir}"
export GTK_EXE_PREFIX="${bundle_dir}"
export GTK_IM_MODULE_FILE="${bundle_dir}/etc/gtk-2.0/gtk.immodules"
export GTK_PATH="${bundle_dir}"
export PANGO_RC_FILE="${bundle_dir}/etc/pango/pangorc"
export XDG_DATA_DIRS="${bundle_dir}/share:$XDG_DATA_DIRS"

ln -sf "${bundle}" /tmp

exec "${bundle_dir}/rawtherapee"
