#!/bin/bash

MACOS="${0%/*}"
#LIB="${MACOS}"/lib
ETC="${MACOS}"/etc

## Environment variables for Quartz and X11 backend
#export DYLD_LIBRARY_PATH="${LIB}:${DYLD_LIBRARY_PATH}" # changed the method @loader_path and @rpath since 2013-02-09
export GTK_PATH="${MACOS}"
export GTK_EXE_PREFIX="${MACOS}"
export GTK_DATA_PREFIX="${MACOS}"
export GTK_DATA_DIRS="${MACOS}"
export GTK2_RC_FILES="${ETC}"/gtk-2.0/gtkrc
export GTK_IM_MODULE_FILE="${ETC}"/gtk-2.0/gtk.immodules
export GDK_PIXBUF_MODULE_FILE="${ETC}"/gtk-2.0/gdk-pixbuf.loaders
export PANGO_RC_FILE="${ETC}"/pango/pangorc
export XDG_DATA_DIRS="${MACOS}"/share

## CUPS library load mode
# RawTherapee build with X11 backend will not load libcups.2.dylib when run on other version Mac OS.
# If you encountered the problem libcups.2.dylib, set this value other than '0'.
CUPS_LOAD_MODE=0

## Environment variables for X11 backend
if [ -d "${ETC}"/fonts ]
then
    export FONTCONFIG_PATH="${ETC}/fonts:${FONTCONFIG_PATH}"
    
    if [ "${CUPS_LOAD_MODE}" = 0 ]
    then
        # Test code since 2013-02
        export DYLD_INSERT_LIBRARIES=/usr/lib/libcups.2.dylib
        export DYLD_FORCE_FLAT_NAMESPACE=1
    else
        # Previous code
        EXTRA_LIBDIR=/tmp/RT4
        [ ! -d ${EXTRA_LIBDIR} ] && mkdir ${EXTRA_LIBDIR}
        cp /usr/lib/libcups* ${EXTRA_LIBDIR}
        export DYLD_LIBRARY_PATH="${EXTRA_LIBDIR}:${DYLD_LIBRARY_PATH}"
    fi
fi

## Symlink for absolute path access
ln -sf "${0%/Contents/*}" /tmp

exec "${MACOS}"/rawtherapee "$@"
