#!/bin/bash

SOURCE_DIR="/usr/local/src/rawtherapee"
BUILD_DIR="${SOURCE_DIR}/build"
GTK_PREFIX="${HOME}/gtk/inst"
FLAGS="-isysroot /Developer/SDKs/MacOSX10.6.sdk -mmacosx-version-min=10.6 -arch x86_64"

declare -x PATH="${HOME}/gtk/inst/bin:${PATH}"
declare -x PKG_CONFIG_PATH="${GTK_PREFIX}/lib/pkgconfig:/opt/local/lib/pkgconfig:${PKG_CONFIG_PATH}"



cmake ()
{
  command cmake \
    -DBUILD_BUNDLE="ON" \
    -DCMAKE_BUILD_TYPE="Release" \
    -DCMAKE_CXX_COMPILER="/opt/local/bin/ccache" \
    -DCMAKE_CXX_COMPILER_ARG1="/opt/local/bin/g++-mp-4.7 ${FLAGS}" \
    -DCMAKE_C_COMPILER="/opt/local/bin/ccache" \
    -DCMAKE_C_COMPILER_ARG1="/opt/local/bin/gcc-mp-4.7 ${FLAGS}" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS="ON" \
    -DOPTION_OMP="ON" \
    -DPROC_TARGET_NUMBER="1" \
    -DRTENGINE_CXX_FLAGS="-ffast-math -funroll-loops -fomit-frame-pointer" \
    ${SOURCE_DIR}
}

{
  cd "${SOURCE_DIR}"
} && {
  [ -d "${BUILD_DIR}" ] && rm -rf "${BUILD_DIR}"
  mkdir "${BUILD_DIR}"
} && {
  cd "${BUILD_DIR}"
  ( cmake && make install -j3 )
}
