#!/bin/sh

source_dir="/usr/local/src/rawtherapee"
build_dir="${source_dir}/build"
finalize_dir="${source_dir}/Release"

flags="-isysroot /Developer/SDKs/MacOSX10.6.sdk -mmacosx-version-min=10.6 -arch x86_64 -lm -I/Library/Frameworks -I/System/Library/Frameworks -I/opt/local/include/gcc47/c++ -I/opt/local/include/gcc47/c++/backward -I/opt/local/include/gcc47/c++/x86_64-apple-darwin10 -I/opt/local/lib/gcc47/gcc/x86_64-apple-darwin10/4.7.1/include -I/opt/local/lib/gcc47/gcc/x86_64-apple-darwin10/4.7.1/include-fixed"

_patch(){
	cp -f ~/GitHub/RawTherapee/tools/osx/info.plist /usr/local/src/rawtherapee/tools/osx/info.plist
	cp -f ~/GitHub/RawTherapee/tools/osx/start /usr/local/src/rawtherapee/tools/osx/start
	cp -f ~/GitHub/RawTherapee/tools/osx/make-app-bundle /usr/local/src/rawtherapee/tools/osx/make-app-bundle
}

_compile(){
	cmake \
		-DBUILD_BUNDLE="ON" \
		-DCMAKE_BUILD_TYPE="Release" \
		-DCMAKE_CXX_COMPILER="/opt/local/bin/ccache" \
		-DCMAKE_CXX_COMPILER_ARG1="/opt/local/bin/g++-mp-4.7 ${flags}" \
		-DCMAKE_C_COMPILER="/opt/local/bin/ccache" \
		-DCMAKE_C_COMPILER_ARG1="/opt/local/bin/gcc-mp-4.7 ${flags}" \
		-DCMAKE_EXPORT_COMPILE_COMMANDS="ON" \
		-DOPTION_OMP="ON" \
		-DPROC_TARGET_NUMBER="1" \
		-DRTENGINE_CXX_FLAGS="-ffast-math -funroll-loops -fomit-frame-pointer" "${source_dir}"
}

_add_comment(){
	sed -i "" \
		-e "4s|ccache|gcc-mp-4|" \
		-e "9s|$| (Development)|" ${finalize_dir}/AboutThisBuild.txt
	
	cat <<-__EOS__ >> ${finalize_dir}/AboutThisBuild.txt
	
	***** Unofficial Bundle for MacOS *****
	
	Bundle created by mattintosh4
	https://github.com/mattintosh4/RawTherapee
	
	Thanks to all developers.
	__EOS__
}

if cd "${source_dir}" ; then
	
	_patch
	
	rm -rf "${build_dir}" "${finalize_dir}"
	mkdir "${build_dir}"
	( cd "${build_dir}" ; _compile && make install -j3 )
	mv "${build_dir}"/Release "${finalize_dir}"
	_add_comment
	./tools/osx/make-app-bundle
else
	return
fi
