#!/bin/sh

export CMAKE_SOURCE_DIR="/usr/local/src/rawtherapee"
cd "${CMAKE_SOURCE_DIR}"

patch -ubN -p0 < ~/GitHub/RawTherapee/patch/start.patch
patch -ubN -p0 < ~/GitHub/RawTherapee/patch/make-app-bundle.patch
patch -ubN -p0 < ~/GitHub/RawTherapee/patch/info.plist.patch

rm -rf ./build ./Release
mkdir build && cd $_

# ARCHITECTURE SETTING
if [ ! "${ARCH}" ]; then
	# DEFAULT
	export ARCH="x86_64"
	# SYSTEM DEFAULT
	# export ARCH=`uname -m`
else
	# CUSTOM
	export ARCH="${ARCH}"
fi

echo "BUILD_ARCHITECTURE: ${ARCH}"

test -x "$HOME/GitHub/RawTherapee/script/compile_commands" && $_ && make install -j3
cd - > /dev/null && mv ./build/Release . && sed \
-i "" \
-e "4s/ccache/gcc-mp-4/" \
-e "9s/$/ (Development)/" "./Release/AboutThisBuild.txt"
cat <<EOF >> ./Release/AboutThisBuild.txt

***** Unofficial Bundle for MacOS *****

Bundle created by mattintosh4
https://github.com/mattintosh4/RawTherapee

Thanks to all developers.
EOF
./tools/osx/make-app-bundle
